apiVersion : apps/v1
kind: Deployment
metadata:
  name: vamsimallejobservices 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vamsimallejobservices
  template:
    metadata:
      labels:
        app: vamsimallejobservices 
    spec:
      containers:
        - name: vamsimallejobservices 
          image: saruku.azurecr.io/vamsimallejobservices
          ports:
          - containerPort: 8000